-- 그룹화
-- 테이블 데이터도 사용 어렵고, 쿼리 복잡해짐
SELECT AVG(SALARY), 1 FROM EMPLOYEE WHERE DEPT_ID = 1
UNION ALL
SELECT AVG(SALARY), 2 FROM EMPLOYEE WHERE DEPT_ID = 2
UNION ALL
SELECT AVG(SALARY), 3 FROM EMPLOYEE WHERE DEPT_ID = 3
UNION ALL
SELECT AVG(SALARY), 4 FROM EMPLOYEE WHERE DEPT_ID = 4;

-- 그룹화를 하면 간결해짐
-- 일반 컬럼 사용 시 GROUP BY에 추가하여 사용
SELECT AVG(SALARY), COUNT(SALARY), DEPT_ID
 	FROM EMPLOYEE
GROUP BY DEPT_ID;

-- HAVING절, 다중행의 필터링
SELECT AVG(SALARY), COUNT(SALARY), DEPT_ID
 	FROM EMPLOYEE
-- WHERE SALARY <= 10000 -- 일반값 필터링
GROUP BY DEPT_ID
HAVING AVG(SALARY) >= 6000
ORDER BY DEPT_ID; -- 다중행 함수 필터링

-- 그룹화 통계
SELECT DEPT_ID, AVG(SALARY), COUNT(SALARY)
	FROM EMPLOYEE
GROUP BY (DEPT_ID)
ORDER BY DEPT_ID;

SELECT NVL(TO_CHAR(DEPT_ID), '--총합--') AS "부서코드"
		, AVG(SALARY)
		, COUNT(SALARY)
	FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_ID)
ORDER BY DEPT_ID;