-- 곱셈 연산자, 비교 연산자
-- 동등 연산자 =
SELECT emp_name, SALARY, SALARY * 12 AS "ANNUAL", HIRE_DATE
  FROM EMPLOYEE
WHERE (SALARY * 12) <> 110808;

-- NOT
SELECT emp_name, SALARY, SALARY * 12 AS "ANNUAL", HIRE_DATE
  FROM EMPLOYEE
WHERE NOT (SALARY * 12) = 110808;

-- IN = OR와 동일
SELECT *
  FROM EMPLOYEE
WHERE DEPT_ID = 1 OR DEPT_ID = 4;

SELECT *
  FROM EMPLOYEE
WHERE DEPT_ID NOT IN (1, 4);

-- BETWEEN
-- hire_date는 날짜형이지만 날짜타입의 문자열과 비교 가능
-- 2022년 한 해 동안 입사한 직원정보 조회
SELECT *
  FROM EMPLOYEE
WHERE HIRE_DATE >= '2022-01-01'
  AND HIRE_DATE <= '2022-12-31';

SELECT *
  FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '2022-01-01' AND '2022-12-31';

SELECT *
  FROM EMPLOYEE
WHERE SALARY BETWEEN 4000 AND 8000;

-- LIKE -문자열에 패턴을 검색
-- % _
-- Seoul: _eo__, %eo%,l _eo% 모두 동일하게 검색
SELECT *
  FROM CUSTOMER
WHERE CITY = 'Busan';

SELECT *
  FROM CUSTOMER
WHERE city LIKE '%eo%';

SELECT *
  FROM CUSTOMER
WHERE city LIKE '_eo%';

SELECT *
  FROM CUSTOMER
WHERE CUST_NAME LIKE 'CUST__'

-- NULL 비교
SELECT *
  FROM CUSTOMER
WHERE city IS NULL; -- '' empty와 다름

-- 집합연산
-- 가상 테이블 -조인, 유니온처럼 쿼리 결과로 나오는 테이블
SELECT PROD_NAME, PRICE
  FROM PRODUCT
WHERE price >= 40000
UNION -- UNION: 중복 제거, UNION ALL: 중복 제거없이 모두 출력
SELECT EMP_NAME , SALARY
  FROM EMPLOYEE
WHERE SALARY >= 9000;
-- 교집합 UNION 대신 INTERSECT 사용