/*
 * This source file was generated by the Gradle 'init' task
 */
package ex05_fileio;

import java.io.*; // java.io 밑에 있는 모든 클래스 사용

public class App {

    public static void main(String[] args) throws IOException {
        System.out.println("파일 쓰고 읽기");

        BufferedWriter bw = new BufferedWriter(new FileWriter("output.txt"));

        bw.write("자바 파일쓰기 입니다");
        bw.newLine();
        bw.write("자바 파일쓰기 테스트");
        bw.close();

        System.out.println("파일 쓰기 완료");

        System.out.println("파일 읽기 시작");
        BufferedReader br = new BufferedReader(new FileReader("output.txt"));

        String line;
        while ((line = br.readLine()) != null) {
            System.out.println(line);
        }

        // 파일 정보 확인
        System.out.println("파일 정보 확인");

        File file = new File("output.txt");
        System.out.println("파일 존재 여부: " + file.exists());
        System.out.println("파일 크기: " + file.length());
        System.out.println("파일 경로: " + file.getAbsolutePath());

        // 람다 함수
        iCalculator add = (int a, int b) -> a + b; // 아주 간단한 로직을 처리하는 함수
        int result = add.calc(5, 6);
        System.out.println("결과: " + result);
    }
}

interface iCalculator {
    int calc(int a, int b);
}