/*
 * This source file was generated by the Gradle 'init' task
 */
package ex02_syntax;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;

public class App {
    
    public static void main(String[] args) {
        int intVal = 10; // 4byte
        long lngVal = 983241729437249873L; // 8byte
        float fltVal = 3.141592f; // 4byte
        double dblVal = 3.141592; // 8byte
        char chrVal = 'A'; // 2byte
        String strVal = "I'm ironman"; // 길이 제한 없음
        boolean boolVal = true;

        // 기본 클래스형, 특수한 이유로 기본형을 클래스화 시킨 타입
        Integer IntValue = 10;
        Long LngValue;
        Float FltValue;
        Double DblValue;
        Character ChrValue;
        Boolean BoolValue;

        // 배열
        int[] arr = {10, 20};
        System.out.println(arr);
        System.out.println(Arrays.toString(arr));

        // 배열을 출력하려면 반복문 사용해야함
    
        // 클래스형
        StringBuffer sb;
        // List, Map, Set ...
        // 직접 만든 클래스를 사용자 정의 자료형으로 사용가능
        ArrayList list = new ArrayList<>(); // 생성자 호출
        list.add(10);
        list.add(20);
        list.add(30);
        
        System.out.println("Hello Java");
        System.out.println(intVal);
        System.out.println(list);

        // HashMap
        HashMap<String, String> sports = new HashMap();
        sports.put("baseball", "10");
        sports.put("basketball", "5");
        sports.put("soccer", "11");

        System.out.println(sports.get("soccer"));

        // HashSet
        HashSet<String> set1 = new HashSet<>(Arrays.asList("H", "e", "l", "l", "o", "!"));
        System.out.println(set1);

        // 형변환
        double dblWorth = intVal; // 작은 데이터형을 큰 데이터형으로 옮길때는 문제 없음
        System.out.println(dblWorth);

        int intWorth = (int)dblVal; // 큰 데이터형을 작은 데이터형으로 옮길 때는 타입을 지정해야함
        System.out.println(intWorth);

        final int number = 123;
        // number = 456; // 오류!

    }
}
